# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app1"
client_id = "c81a2d0010b357812d99b6f89cf91183"
application_url = "https://referring-garage-apps-soil.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://referring-garage-apps-soil.trycloudflare.com/auth/callback",
  "https://referring-garage-apps-soil.trycloudflare.com/auth/shopify/callback",
  "https://referring-garage-apps-soil.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abhimanyu-propero.myshopify.com"
